clear; close all; clc;
omg0 = 0.5;   %Passband frequency (times pi!)
omg1 = 0.6;   %Passband frequency (times pi!)
rp = 1;   %Passband ripple in dB
a = 20;   %Stopband attenuation in dB
d0 = designfilt('lowpassiir', ...
    'DesignMethod',         'butter', ...
    'PassbandFrequency',    omg0, ...
    'StopbandFrequency',    omg1, ...
    'PassbandRipple',       rp, ...
    'StopbandAttenuation',  a);
d1 = designfilt('lowpassiir', ...
    'DesignMethod',         'cheby1', ...
    'PassbandFrequency',    omg0, ...
    'StopbandFrequency',    omg1, ...
    'PassbandRipple',       rp, ...
    'StopbandAttenuation',  a);
d2 = designfilt('lowpassiir', ...
    'DesignMethod',         'cheby2', ...
    'PassbandFrequency',    omg0, ...
    'StopbandFrequency',    omg1, ...
    'PassbandRipple',       rp, ...
    'StopbandAttenuation',  a);
d3 = designfilt('lowpassiir', ...
    'DesignMethod',         'ellip', ...
    'PassbandFrequency',    omg0, ...
    'StopbandFrequency',    omg1, ...
    'PassbandRipple',       rp, ...
    'StopbandAttenuation',  a);
fvtool(d0, d1, d2, d3);
[d0.filtord, d1.filtord, d2.filtord, d3.filtord]

